### CREATE USER : SIGNUP 

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "nolan@gmail.com",
    "password": "tttt"
}

### Connect USER : SIGNIN
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "nolan@gmail.com",
    "password": "tttt"
}

### GET USER BY ID 
GET http://localhost:3000/auth/5

### GET USER BY EMAIL
GET http://localhost:3000/auth?email=bob@gmail.com

### GET USER BY EMAIL
GET http://localhost:3000/auth?email=alice@gmail.com

