### CREATE USER : SIGNUP 

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "ttest"
}

### Connect USER : SIGNIN
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "nolan@gmail.com",
    "password": "tttt"
}

### Witch USER : WHOAMI
POST http://localhost:3000/auth/whoAmI
Content-Type: application/json

### Signout USER : SINGOUT
POST http://localhost:3000/auth/signout
Content-Type: application/json

### GET USER BY ID 
GET http://localhost:3000/auth/5

### GET USER BY EMAIL
GET http://localhost:3000/auth?email=bob@gmail.com

### GET USER BY EMAIL
GET http://localhost:3000/auth?email=alice@gmail.com

